// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementSystem.API.Data;

#nullable disable

namespace RecruitmentManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104191246_jobskills")]
    partial class jobskills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.Property<Guid>("ApplicationSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasSkill")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationSkillId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Property<Guid>("AssignedReviewersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("Uid");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.Property<Guid>("CVReviewStageSid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedReviewersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CVReviewStageSid");

                    b.HasIndex("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("ReviewedByUid");

                    b.ToTable("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.Property<Guid>("CVStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CVStorageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CVStorages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Address = "123 Main Street, Apartment 4B",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400001",
                            State = "Maharashtra",
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateSkillId = new Guid("7716193f-2188-4524-a1d5-b70e4a72f875"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("9ea15407-71d6-4911-8675-6cc4aafc8235")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("97f1dc14-2aa0-4b07-a469-d8fbe64832d5"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("77aaadce-bb82-4718-a20a-5fc5a20499ee")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("94030797-f5af-41cc-a13b-110cafe4c556"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("9cc814bf-6240-4f3b-bd07-0920f765da90")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.Property<Guid>("CandidateSocialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocialPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSocialsId");

                    b.HasIndex("SocialPlatformId");

                    b.HasIndex("CandidateProfileId", "SocialPlatformId")
                        .IsUnique();

                    b.ToTable("CandidateSocials");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = new Guid("b3f2c0e1-6f2a-4a6c-9f8a-1a2b3c4d5e01"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science",
                            InstituteName = "St. Xavier's College, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 78.45m,
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("c4d3f1a2-7b3c-4d8e-9a0b-2c3d4e5f6a02"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "Higher Secondary (12th)",
                            EndDate = new DateTime(2016, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "Mumbai Central Higher Secondary School",
                            IsCurrent = false,
                            PercentageScore = 86.20m,
                            StartDate = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeRoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            IsActive = true,
                            RoleName = "Recruiter"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            IsActive = true,
                            RoleName = "Reviewer"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            IsActive = true,
                            RoleName = "Interviewer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EmployeeRoleId");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("EmployeeUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            AssignedOn = new DateTime(2026, 1, 4, 19, 12, 45, 562, DateTimeKind.Utc).AddTicks(7408)
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            AssignedOn = new DateTime(2026, 1, 4, 19, 12, 45, 562, DateTimeKind.Utc).AddTicks(7411)
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            AssignedOn = new DateTime(2026, 1, 4, 19, 12, 45, 562, DateTimeKind.Utc).AddTicks(7413)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("d5e4f3b2-8c4d-4e9f-0a1b-3c4d5e6f7a03"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "InnoTech Solutions Pvt. Ltd.",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on backend APIs using .NET Core, implemented authentication and REST endpoints, wrote unit tests and integrated CI/CD pipelines.",
                            Position = "Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("e6f5a4c3-9d5e-4f0a-1b2c-4d5e6f7a8b04"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "QuickStart Internships",
                            DurationYears = 0.50m,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Assisted in developing small features, bug fixes and wrote documentation. Gained exposure to agile practices.",
                            Position = "Software Intern",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = new Guid("e481d97e-7cba-4200-9e04-79edf2916c71"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 25, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7260),
                            DeadlineDate = new DateTime(2026, 1, 24, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7267),
                            JobDescriptionId = new Guid("09f9f319-b455-4f2c-8bff-433f885f9f14"),
                            OpeningsCount = 3
                        },
                        new
                        {
                            JobId = new Guid("3fc609ee-2ad3-4023-9d1f-8f22f17142b3"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 28, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7272),
                            DeadlineDate = new DateTime(2026, 1, 27, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7273),
                            JobDescriptionId = new Guid("2a778506-fc46-41e3-be10-f77e1cfab8d3"),
                            OpeningsCount = 2
                        },
                        new
                        {
                            JobId = new Guid("41796f1f-bcdf-4127-ab13-8283e744f0b0"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 30, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7279),
                            DeadlineDate = new DateTime(2026, 1, 29, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7280),
                            JobDescriptionId = new Guid("50b43ef2-d999-49e7-b025-4b6ae1971067"),
                            OpeningsCount = 1
                        },
                        new
                        {
                            JobId = new Guid("3cc51923-b38a-4eda-8523-6577d2b63e54"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 1, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7283),
                            DeadlineDate = new DateTime(2026, 2, 3, 19, 12, 45, 564, DateTimeKind.Utc).AddTicks(7284),
                            JobDescriptionId = new Guid("d95bf6ed-1ac2-41be-b483-f32a09c02d6f"),
                            OpeningsCount = 5
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumExperienceReq")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            JobDescriptionId = new Guid("09f9f319-b455-4f2c-8bff-433f885f9f14"),
                            Details = "We are looking for an experienced .NET developer to join our team. Must have strong C# and ASP.NET Core skills.",
                            JobTypeId = new Guid("64018c1a-a5e7-4b5b-9189-1d893c40d658"),
                            Location = "Mumbai, India",
                            MinimumExperienceReq = 5,
                            Responsibilty = "Develop and maintain web applications, code reviews, mentor junior developers",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("2a778506-fc46-41e3-be10-f77e1cfab8d3"),
                            Details = "Join our frontend team to build modern web applications using React and TypeScript.",
                            JobTypeId = new Guid("64018c1a-a5e7-4b5b-9189-1d893c40d658"),
                            Location = "Bangalore, India",
                            MinimumExperienceReq = 3,
                            Responsibilty = "Build responsive UIs, optimize performance, collaborate with designers",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("50b43ef2-d999-49e7-b025-4b6ae1971067"),
                            Details = "Seeking a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.",
                            JobTypeId = new Guid("65ed2e33-e49c-48ad-8df5-9140922f2aff"),
                            Location = "Remote",
                            MinimumExperienceReq = 4,
                            Responsibilty = "Maintain AWS infrastructure, automate deployments, monitor systems",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("d95bf6ed-1ac2-41be-b483-f32a09c02d6f"),
                            Details = "Entry-level position for fresh graduates passionate about Python and data science.",
                            JobTypeId = new Guid("7c14f709-c074-4485-95b9-9518cec5f63e"),
                            Location = "Pune, India",
                            MinimumExperienceReq = 0,
                            Responsibilty = "Write clean code, learn from seniors, contribute to data pipelines",
                            Title = "Junior Python Developer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.Property<Guid>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSkillId");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            JobTypeId = new Guid("64018c1a-a5e7-4b5b-9189-1d893c40d658"),
                            TypeName = "Full-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("7c14f709-c074-4485-95b9-9518cec5f63e"),
                            TypeName = "Part-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("65ed2e33-e49c-48ad-8df5-9140922f2aff"),
                            TypeName = "Contract"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.Property<Guid>("ReviewCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommentedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewCommentId");

                    b.HasIndex("CommentedByUid");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("9ea15407-71d6-4911-8675-6cc4aafc8235"),
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("77aaadce-bb82-4718-a20a-5fc5a20499ee"),
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = new Guid("584982bb-daa0-4e75-9e87-6901649b95d5"),
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            SkillId = new Guid("21def8c2-dd58-478a-8271-018ec1fe40d7"),
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = new Guid("5856875e-78fb-4efd-86c0-24e8857972e0"),
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("9cc814bf-6240-4f3b-bd07-0920f765da90"),
                            IsActive = true,
                            Name = "React"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.SocialPlatform", b =>
                {
                    b.Property<Guid>("SocialPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialPlatformId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            SocialPlatformId = new Guid("d338060a-30cc-4275-b80f-88d427fa32a9"),
                            Name = "LinkedIn"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("468a9d7a-8cbc-4d25-828e-f01121c743d8"),
                            Name = "GitHub"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("84f68276-1a61-46ab-826e-ae3ca5261904"),
                            Name = "Portfolio"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("8c4df48a-e952-4dee-a238-7a8a0b31b2da"),
                            Name = "Twitter"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("6459d3b0-2e54-4357-ab5a-c89c2819b733"),
                            Name = "Stack Overflow"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a01a33a1-10c5-4424-a74b-0130a086b96e"),
                            CreatedDate = new DateTime(2026, 1, 4, 19, 12, 45, 59, DateTimeKind.Utc).AddTicks(9933),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exp.com",
                            Fname = "Admin",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "User",
                            MobileNumber = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAECQ5fN3t4YB0h9x0hy6oQXJG5o1wfYKJdeXENg2u3wrgBLIGmdIOvMyuPWI4uRJmmw==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 4, 19, 12, 45, 162, DateTimeKind.Utc).AddTicks(7102),
                            DOB = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@exp.com",
                            Fname = "Peter",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Parker",
                            MobileNumber = "0987654321",
                            PasswordHash = "AQAAAAIAAYagAAAAEF3m9oMrSOOI9JWJk7O5dzM/SlZIJKnPnqL8LoFOMwXKKQMhpCgnWDGr6lh55WPvPQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733"),
                            CreatedDate = new DateTime(2026, 1, 4, 19, 12, 45, 276, DateTimeKind.Utc).AddTicks(1167),
                            DOB = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abhi@exp.com",
                            Fname = "Abhi",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "G",
                            MobileNumber = "1111111111",
                            PasswordHash = "AQAAAAIAAYagAAAAEI/efDdoMabi0zn20nkssvL9HJK4b2iRkk1tlmTIMa02DLhHAHJzNns9WyVXMMuaGw==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 4, 19, 12, 45, 373, DateTimeKind.Utc).AddTicks(2220),
                            DOB = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reviewer@exp.com",
                            Fname = "Bruce",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Wayne",
                            MobileNumber = "2222222222",
                            PasswordHash = "AQAAAAIAAYagAAAAELj1vGG2La5FwXdCTuAEH/nFf6NAvsVwvTf83meuUyNlkLtdsVsU30JabLzO2pj98A==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 4, 19, 12, 45, 470, DateTimeKind.Utc).AddTicks(6011),
                            DOB = new DateTime(1988, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "interviewer@exp.com",
                            Fname = "Tony",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Stark",
                            MobileNumber = "3333333333",
                            PasswordHash = "AQAAAAIAAYagAAAAEHf9Ga3UJ8oMZDFicAgpfi/ljqdMsjxMMe8XF4zI3sGaobcwwPJBlq3zvzPwlGv92w==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Property<Guid>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122"),
                            TypeName = "Candidate",
                            active = true
                        },
                        new
                        {
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e"),
                            TypeName = "Employee",
                            active = true
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", null)
                        .WithMany("AssignedReviewers")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.AssignedReviewer", null)
                        .WithMany("CVReviewStages")
                        .HasForeignKey("AssignedReviewersId");

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("CVReviewStages")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedByUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CVStorages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentManagementSystem.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSocials")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.SocialPlatform", "SocialPlatform")
                        .WithMany()
                        .HasForeignKey("SocialPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CommentedBy")
                        .WithMany()
                        .HasForeignKey("CommentedByUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ReviewComments")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedBy");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Navigation("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("CVStorages");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateSocials");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Navigation("ApplicationSkills");

                    b.Navigation("AssignedReviewers");

                    b.Navigation("CVReviewStages");

                    b.Navigation("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
