// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementSystem.API.Data;

#nullable disable

namespace RecruitmentManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107065144_seedValues TryAgain")]
    partial class seedValuesTryAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationInterviewRound", b =>
                {
                    b.Property<Guid>("ApplicationInterviewRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeetLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationInterviewRoundId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ApplicationInterviewRounds");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.Property<Guid>("ApplicationSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasSkill")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationSkillId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Property<Guid>("AssignedReviewersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.Property<Guid>("CVStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CVStorageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CVStorages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            Address = "A-304, Sunrise Apartments, Koramangala",
                            City = "Bangalore",
                            Country = "India",
                            PostalCode = "560034",
                            State = "Karnataka",
                            UserId = new Guid("050e7b3e-092f-49ec-9672-3ece1fb4b1c0")
                        },
                        new
                        {
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            Address = "B-12, Green Valley Society, Bandra West",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400050",
                            State = "Maharashtra",
                            UserId = new Guid("73f67ee8-ef98-4a52-b6b6-9b8a693795de")
                        },
                        new
                        {
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Address = "123 Main Street, Apartment 4B",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400001",
                            State = "Maharashtra",
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateSkillId = new Guid("067be206-7456-4c11-8c24-2a3fdebab7f8"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("87c5a754-821a-45af-a793-3d636f0ad9d4"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("664ecdbe-1a9e-4a56-a72e-3e1d122646ee"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("272e9202-e704-4abd-af25-9d995ff2e61e"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("40e578a5-9408-4da2-b7d1-2618ee444ad1"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("275d0b0e-6d60-4c3a-ab77-1edfeff21a32"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            ExperienceYears = 6m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("bef15313-d642-4d37-b8d2-0e5177a423c1"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.Property<Guid>("CandidateSocialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocialPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSocialsId");

                    b.HasIndex("SocialPlatformId");

                    b.HasIndex("CandidateProfileId", "SocialPlatformId")
                        .IsUnique();

                    b.ToTable("CandidateSocials");

                    b.HasData(
                        new
                        {
                            CandidateSocialsId = new Guid("f9812cae-0de3-4097-8270-5c9798c7b13d"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            Link = "https://linkedin.com/in/priya-sharma-dev",
                            SocialPlatformId = new Guid("e51d1a21-66ec-4480-92e8-12aea0b34920")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("26fb87cb-78ce-4b52-9ae3-2ba53ea874fc"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            Link = "https://github.com/priyasharma",
                            SocialPlatformId = new Guid("751a7e1c-df12-4bdc-a278-f0f7effc4e08")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("7cff6c8c-a3ef-4950-b9c0-b64d340c0e5b"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            Link = "https://linkedin.com/in/rajesh-kumar-frontend",
                            SocialPlatformId = new Guid("e51d1a21-66ec-4480-92e8-12aea0b34920")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("be97a527-e891-4a4a-8db2-b171c544216f"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            Link = "https://github.com/rajeshkumar-dev",
                            SocialPlatformId = new Guid("751a7e1c-df12-4bdc-a278-f0f7effc4e08")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("9e617234-950b-4669-b31a-0c009f299865"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            Link = "https://rajeshkumar.dev",
                            SocialPlatformId = new Guid("333fab14-c62b-4ab7-886e-e880bab313b1")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("1aac2239-885b-4659-a20e-cd95dbcf10aa"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Link = "https://linkedin.com/in/test-user",
                            SocialPlatformId = new Guid("e51d1a21-66ec-4480-92e8-12aea0b34920")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("c0782ba6-8d48-45ca-bfcf-c082bfb66ed5"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Link = "https://github.com/testuser",
                            SocialPlatformId = new Guid("751a7e1c-df12-4bdc-a278-f0f7effc4e08")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = new Guid("5e049841-411d-4588-926e-9010f05e19b3"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            DegreeType = "B.E",
                            EndDate = new DateTime(2017, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science and Engineering",
                            InstituteName = "RV College of Engineering, Bangalore",
                            IsCurrent = false,
                            PercentageScore = 82.50m,
                            StartDate = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("5658a065-4768-4745-aa39-6e2fbc9b5d3f"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            DegreeType = "12th Grade",
                            EndDate = new DateTime(2013, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science (PCMC)",
                            InstituteName = "National Public School, Bangalore",
                            IsCurrent = false,
                            PercentageScore = 89.00m,
                            StartDate = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("ce49424d-a625-4e59-b194-4153a0cf882d"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Information Technology",
                            InstituteName = "Mumbai University - DJ Sanghvi College",
                            IsCurrent = false,
                            PercentageScore = 75.20m,
                            StartDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("a4808bab-76ec-40ce-a214-b5c7e20313be"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            DegreeType = "HSC (12th)",
                            EndDate = new DateTime(2015, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "St. Xavier's High School, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 81.50m,
                            StartDate = new DateTime(2013, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("b3f2c0e1-6f2a-4a6c-9f8a-1a2b3c4d5e01"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science",
                            InstituteName = "St. Xavier's College, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 78.45m,
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("c4d3f1a2-7b3c-4d8e-9a0b-2c3d4e5f6a02"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "Higher Secondary (12th)",
                            EndDate = new DateTime(2016, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "Mumbai Central Higher Secondary School",
                            IsCurrent = false,
                            PercentageScore = 86.20m,
                            StartDate = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeRoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            IsActive = true,
                            RoleName = "Recruiter"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            IsActive = true,
                            RoleName = "Reviewer"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            IsActive = true,
                            RoleName = "Interviewer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EmployeeRoleId");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("EmployeeUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            AssignedOn = new DateTime(2026, 1, 7, 6, 51, 41, 810, DateTimeKind.Utc).AddTicks(1447)
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            AssignedOn = new DateTime(2026, 1, 7, 6, 51, 41, 810, DateTimeKind.Utc).AddTicks(1450)
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            AssignedOn = new DateTime(2026, 1, 7, 6, 51, 41, 810, DateTimeKind.Utc).AddTicks(1453)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("76aa471e-03a2-4fce-959d-94c38e88bc02"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            CompanyName = "Infosys Technologies Ltd",
                            DurationYears = 3.50m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Led a team of 4 developers in building enterprise applications using .NET Core and Angular. Implemented microservices architecture, optimized database queries, and mentored junior developers.",
                            Position = "Senior Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("ccc773a8-36b8-43d0-84d7-9e4bd50ae17a"),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            CompanyName = "TCS Digital",
                            DurationYears = 3.00m,
                            EndDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Developed and maintained web applications using ASP.NET MVC and SQL Server. Participated in code reviews, unit testing, and agile ceremonies.",
                            Position = "Software Developer",
                            StartDate = new DateTime(2017, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("72860a21-dfdf-4432-b87c-3e099edc9e53"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            CompanyName = "Wipro Digital",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Built responsive web applications using React, Redux, and TypeScript. Collaborated with UX designers and backend teams to deliver pixel-perfect interfaces. Improved page load times by 40%.",
                            Position = "Frontend Developer",
                            StartDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("35a1d804-622a-4f0d-96aa-5dcec6509e6d"),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            CompanyName = "Cognizant",
                            DurationYears = 1.50m,
                            EndDate = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on client projects using HTML, CSS, JavaScript, and basic React. Fixed bugs, implemented new features, and learned modern frontend development practices.",
                            Position = "Junior Frontend Developer",
                            StartDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("d5e4f3b2-8c4d-4e9f-0a1b-3c4d5e6f7a03"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "InnoTech Solutions Pvt. Ltd.",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on backend APIs using .NET Core, implemented authentication and REST endpoints, wrote unit tests and integrated CI/CD pipelines.",
                            Position = "Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("e6f5a4c3-9d5e-4f0a-1b2c-4d5e6f7a8b04"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "QuickStart Internships",
                            DurationYears = 0.50m,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Assisted in developing small features, bug fixes and wrote documentation. Gained exposure to agile practices.",
                            Position = "Software Intern",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.InterviewPanelMember", b =>
                {
                    b.Property<Guid>("InterviewPanelMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationInterviewRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InterviewPanelMemberId");

                    b.HasIndex("ApplicationInterviewRoundId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("InterviewerId");

                    b.ToTable("InterviewPanelMembers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DefaultInterviewRoundsDefined")
                        .HasColumnType("bit");

                    b.Property<bool>("DefaultReviewersAssigned")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 28, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7876),
                            DeadlineDate = new DateTime(2026, 1, 27, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7884),
                            DefaultInterviewRoundsDefined = false,
                            DefaultReviewersAssigned = false,
                            JobDescriptionId = new Guid("17c3c873-e9b4-40c7-aa1e-f4a15215c2dd"),
                            OpeningsCount = 3
                        },
                        new
                        {
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 31, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7888),
                            DeadlineDate = new DateTime(2026, 1, 30, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7889),
                            DefaultInterviewRoundsDefined = false,
                            DefaultReviewersAssigned = false,
                            JobDescriptionId = new Guid("1b0c489e-b0aa-42f0-8970-5ae1d05d5aac"),
                            OpeningsCount = 2
                        },
                        new
                        {
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 2, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7891),
                            DeadlineDate = new DateTime(2026, 2, 1, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7914),
                            DefaultInterviewRoundsDefined = false,
                            DefaultReviewersAssigned = false,
                            JobDescriptionId = new Guid("2419e70e-58bb-4f99-a148-6df838e294c8"),
                            OpeningsCount = 1
                        },
                        new
                        {
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 4, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7918),
                            DeadlineDate = new DateTime(2026, 2, 6, 6, 51, 41, 811, DateTimeKind.Utc).AddTicks(7918),
                            DefaultInterviewRoundsDefined = false,
                            DefaultReviewersAssigned = false,
                            JobDescriptionId = new Guid("1a116292-6aa5-41fd-bcd1-ec7122f1ade2"),
                            OpeningsCount = 5
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            JobApplicationId = new Guid("d9a8985e-31f8-4f3f-b2ba-80353eb85830"),
                            ApplicationDate = new DateTime(2025, 12, 30, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5148),
                            CandidateProfileId = new Guid("dcc9d83d-b11c-4336-9d33-fcc89185962b"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            StatusUpdatedAt = new DateTime(2025, 12, 30, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5153)
                        },
                        new
                        {
                            JobApplicationId = new Guid("84b87be3-be72-440f-bbca-be8349477595"),
                            ApplicationDate = new DateTime(2025, 12, 31, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5198),
                            CandidateProfileId = new Guid("e1192660-3fe6-4244-a740-5c0325674394"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            StatusUpdatedAt = new DateTime(2025, 12, 31, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            JobApplicationId = new Guid("030d361c-2b38-4fdf-badc-9e4db3029fd6"),
                            ApplicationDate = new DateTime(2026, 1, 1, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5228),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            StatusNote = "Application received",
                            StatusUpdatedAt = new DateTime(2026, 1, 1, 6, 51, 41, 813, DateTimeKind.Utc).AddTicks(5230)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumExperienceReq")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            JobDescriptionId = new Guid("17c3c873-e9b4-40c7-aa1e-f4a15215c2dd"),
                            Details = "We are looking for an experienced .NET developer to join our team. Must have strong C# and ASP.NET Core skills.",
                            JobTypeId = new Guid("14bed5b8-6c9c-4029-8e39-b78995af3c12"),
                            Location = "Mumbai, India",
                            MinimumExperienceReq = 5,
                            Responsibilty = "Develop and maintain web applications, code reviews, mentor junior developers",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("1b0c489e-b0aa-42f0-8970-5ae1d05d5aac"),
                            Details = "Join our frontend team to build modern web applications using React and TypeScript.",
                            JobTypeId = new Guid("14bed5b8-6c9c-4029-8e39-b78995af3c12"),
                            Location = "Bangalore, India",
                            MinimumExperienceReq = 3,
                            Responsibilty = "Build responsive UIs, optimize performance, collaborate with designers",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("2419e70e-58bb-4f99-a148-6df838e294c8"),
                            Details = "Seeking a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.",
                            JobTypeId = new Guid("edfe6e5a-c18c-44dd-9cd0-c7f8a5b66fa3"),
                            Location = "Remote",
                            MinimumExperienceReq = 4,
                            Responsibilty = "Maintain AWS infrastructure, automate deployments, monitor systems",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("1a116292-6aa5-41fd-bcd1-ec7122f1ade2"),
                            Details = "Entry-level position for fresh graduates passionate about Python and data science.",
                            JobTypeId = new Guid("e6e80f02-6b06-4abf-aa82-49da5e69c2da"),
                            Location = "Pune, India",
                            MinimumExperienceReq = 0,
                            Responsibilty = "Write clean code, learn from seniors, contribute to data pipelines",
                            Title = "Junior Python Developer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobInterviewRound", b =>
                {
                    b.Property<Guid>("JobInterviewRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobInterviewRoundId");

                    b.HasIndex("JobId");

                    b.ToTable("JobInterviewRounds");

                    b.HasData(
                        new
                        {
                            JobInterviewRoundId = new Guid("e568248f-02f4-4f47-998b-e2ff63680ef9"),
                            IsActive = true,
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            RoundNumber = 1,
                            RoundType = "Technical"
                        },
                        new
                        {
                            JobInterviewRoundId = new Guid("7cec740e-e176-4299-b690-b322be0e4550"),
                            IsActive = true,
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            RoundNumber = 2,
                            RoundType = "Technical"
                        },
                        new
                        {
                            JobInterviewRoundId = new Guid("e70a92b2-202b-4aee-b6ab-ef1f9678b1f2"),
                            IsActive = true,
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            RoundNumber = 3,
                            RoundType = "HR"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.Property<Guid>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSkillId");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            JobSkillId = new Guid("8a2cba7c-77e8-4816-9ff5-f87d7e43f4b7"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 5,
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            JobSkillId = new Guid("ecb67307-ce9e-42fa-9668-1c0fb320d2e6"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            JobSkillId = new Guid("204564ab-5f09-4156-b852-e0c75ab4e8a5"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            JobSkillId = new Guid("c464e2c6-6050-4260-b203-7e1eb0e7ced9"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            JobSkillId = new Guid("47439964-3f47-4233-a5e0-41113a3f4793"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868")
                        },
                        new
                        {
                            JobSkillId = new Guid("c1a03393-44c2-4f48-aa7a-fb364b4f663d"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            JobSkillId = new Guid("a384ecac-d7c3-426c-bf2c-1081c7839566"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868")
                        },
                        new
                        {
                            JobSkillId = new Guid("75bc4b90-27d1-421a-b41d-69dac1af8455"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            JobSkillId = new Guid("6b19d5c5-e470-4c50-b0f9-3b85dfe93d9c"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            JobSkillId = new Guid("d69a6744-7c00-4084-b53e-924cb685fec8"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            JobSkillId = new Guid("b862cb8b-4110-4618-b052-25f04e8791b9"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            JobSkillId = new Guid("711d5cb7-f06d-49f7-b8c5-6bdad400c6aa"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            JobSkillId = new Guid("554a8a63-e8ec-4205-9f61-bf04f183ec80"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("4c487bbc-6fa9-4643-9d9e-a88e5bea917e")
                        },
                        new
                        {
                            JobSkillId = new Guid("015cb29d-f6b6-4083-a1aa-2436063f7097"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            JobSkillId = new Guid("e7d891b0-bd82-4b3d-b061-0e0d08ad12ed"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("4c487bbc-6fa9-4643-9d9e-a88e5bea917e")
                        },
                        new
                        {
                            JobSkillId = new Guid("63ae3a18-a97a-47eb-9526-684b3fcadfb7"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            JobSkillId = new Guid("5706cb4f-c47d-4702-bbe7-37066b4654aa"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            JobTypeId = new Guid("14bed5b8-6c9c-4029-8e39-b78995af3c12"),
                            TypeName = "Full-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("e6e80f02-6b06-4abf-aa82-49da5e69c2da"),
                            TypeName = "Part-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("edfe6e5a-c18c-44dd-9cd0-c7f8a5b66fa3"),
                            TypeName = "Contract"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.Property<Guid>("ReviewCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommentedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewCommentId");

                    b.HasIndex("CommentedByUid");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882"),
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6"),
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0"),
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895"),
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868"),
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0"),
                            IsActive = true,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = new Guid("4c487bbc-6fa9-4643-9d9e-a88e5bea917e"),
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("92dc292b-9df8-419a-8424-8939f94f3c98"),
                            IsActive = true,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.SocialPlatform", b =>
                {
                    b.Property<Guid>("SocialPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialPlatformId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            SocialPlatformId = new Guid("e51d1a21-66ec-4480-92e8-12aea0b34920"),
                            Name = "LinkedIn"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("751a7e1c-df12-4bdc-a278-f0f7effc4e08"),
                            Name = "GitHub"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("333fab14-c62b-4ab7-886e-e880bab313b1"),
                            Name = "Portfolio"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("4272cb07-04bd-4a8b-a0cc-fc6b3ff6d9db"),
                            Name = "Twitter"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("9cf3933d-2973-4340-afb8-14404c20613a"),
                            Name = "Stack Overflow"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a01a33a1-10c5-4424-a74b-0130a086b96e"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 40, 693, DateTimeKind.Utc).AddTicks(4863),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exp.com",
                            Fname = "Admin",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "User",
                            MobileNumber = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAEPoBDRTPnukxjvAoF5MWR/p5NPfr0C1bzO+qODxj87Zh9yoKDYMrc9fug4wod1YwlQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 40, 814, DateTimeKind.Utc).AddTicks(5826),
                            DOB = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@exp.com",
                            Fname = "Peter",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Parker",
                            MobileNumber = "0987654321",
                            PasswordHash = "AQAAAAIAAYagAAAAELrvIzKRZexwxKRoVgSZ3G3WZvpeVVLFadF7f7+O0ZWexQT0gMOfZgoIN0ADmsDLww==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 40, 913, DateTimeKind.Utc).AddTicks(3704),
                            DOB = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reviewer@exp.com",
                            Fname = "Bruce",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Wayne",
                            MobileNumber = "2222222222",
                            PasswordHash = "AQAAAAIAAYagAAAAED06tgsAywnF52MFHjLtutzqon5nbMlAsCtbSgtesJr21nRyNRbZR3WdYnG0M74LkQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 19, DateTimeKind.Utc).AddTicks(5200),
                            DOB = new DateTime(1988, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "interviewer@exp.com",
                            Fname = "Tony",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Stark",
                            MobileNumber = "3333333333",
                            PasswordHash = "AQAAAAIAAYagAAAAEMRUdP0Hnjhg97MMulTwxC42rDkbphJYx8Z5aDvTxE+xQEkFcA9+X0wapoGGNBW7fw==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("050e7b3e-092f-49ec-9672-3ece1fb4b1c0"),
                            CreatedDate = new DateTime(2025, 7, 7, 6, 51, 41, 118, DateTimeKind.Utc).AddTicks(14),
                            DOB = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.sharma@email.com",
                            Fname = "Priya",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Sharma",
                            MobileNumber = "9876543210",
                            PasswordHash = "AQAAAAIAAYagAAAAEJmQ2XbKnH6vPSZOecXP7jW3tYAMxJ83GXwE3Qlcixszvn2CKvST9xCa3PGc+Dv3sA==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("73f67ee8-ef98-4a52-b6b6-9b8a693795de"),
                            CreatedDate = new DateTime(2025, 9, 7, 6, 51, 41, 219, DateTimeKind.Utc).AddTicks(6584),
                            DOB = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rajesh.kumar@email.com",
                            Fname = "Rajesh",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Kumar",
                            MobileNumber = "9876543211",
                            PasswordHash = "AQAAAAIAAYagAAAAEKxSBElM6wKau4uIBv+K5mI7NKqIBis3Gb9rkMJMmBCkjoZDAok849tdbaKEWs0KIg==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 316, DateTimeKind.Utc).AddTicks(7691),
                            DOB = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abhi@exp.com",
                            Fname = "Abhi",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "G",
                            MobileNumber = "1111111111",
                            PasswordHash = "AQAAAAIAAYagAAAAENOyMaiAC5vNJPF0kbPdT2SJZS9on6Xjxqy5m26s8TIxeW0hhaajxBrjg206QJ7tuA==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("24b407f3-f31c-4c5c-b78c-ca26a846d878"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 422, DateTimeKind.Utc).AddTicks(7889),
                            DOB = new DateTime(1990, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@exp.com",
                            Fname = "Rahul",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Sharma",
                            MobileNumber = "9000000001",
                            PasswordHash = "AQAAAAIAAYagAAAAEPyOU7384Iuuju9uqUVatPl+S3Rjp492FPqRrVYq7uMSwLXmITPbQ/w0svP/tsMrBA==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("4633f56a-dac2-4601-89f5-220bc8782d54"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 517, DateTimeKind.Utc).AddTicks(944),
                            DOB = new DateTime(1992, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya@exp.com",
                            Fname = "Priya",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Verma",
                            MobileNumber = "9000000002",
                            PasswordHash = "AQAAAAIAAYagAAAAEPphsWsw0+BHWLnXPyJ3KgUBIf75mD1yEm+TL5ahHaH04PoNYMtOuBp+MB9zgJgKvA==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("cb7a41c2-d3e3-4aef-9f17-e4f07c234716"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 615, DateTimeKind.Utc).AddTicks(9643),
                            DOB = new DateTime(1989, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amit@exp.com",
                            Fname = "Amit",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Kumar",
                            MobileNumber = "9000000003",
                            PasswordHash = "AQAAAAIAAYagAAAAELAeLg+3AhAZc12s9i/xDavHL4eRe9FCsjlNOXDDAv3I3goNUfq0DJyJIxo2NJDTNQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("f1990cb6-5bd3-44de-9c5b-e0249a796862"),
                            CreatedDate = new DateTime(2026, 1, 7, 6, 51, 41, 708, DateTimeKind.Utc).AddTicks(2709),
                            DOB = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sneha@exp.com",
                            Fname = "Sneha",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Reddy",
                            MobileNumber = "9000000004",
                            PasswordHash = "AQAAAAIAAYagAAAAEAP18mZKTY5BNRkNywce5VcKmTZoDqN6xHIeL9XxUbUn9Z2oCLAQJ2ALHMPs3ADCiA==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Property<Guid>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122"),
                            TypeName = "Candidate",
                            active = true
                        },
                        new
                        {
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e"),
                            TypeName = "Employee",
                            active = true
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationInterviewRound", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", null)
                        .WithMany("AssignedReviewers")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CVStorages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentManagementSystem.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSocials")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.SocialPlatform", "SocialPlatform")
                        .WithMany()
                        .HasForeignKey("SocialPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.InterviewPanelMember", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.ApplicationInterviewRound", "ApplicationInterviewRound")
                        .WithMany("PanelMembers")
                        .HasForeignKey("ApplicationInterviewRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationInterviewRound");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobInterviewRound", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CommentedBy")
                        .WithMany()
                        .HasForeignKey("CommentedByUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ReviewComments")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedBy");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationInterviewRound", b =>
                {
                    b.Navigation("PanelMembers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("CVStorages");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateSocials");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Navigation("ApplicationSkills");

                    b.Navigation("AssignedReviewers");

                    b.Navigation("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
