// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementSystem.API.Data;

#nullable disable

namespace RecruitmentManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102035736_update seed")]
    partial class updateseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Property<Guid>("AssignedReviewersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AssignedReviewersId");

                    b.HasIndex("Uid");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.Property<Guid>("CVReviewStageSid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedReviewersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CVReviewStageSid");

                    b.HasIndex("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("ReviewedByUid");

                    b.ToTable("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.Property<Guid>("CVStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CVStorageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CVStorages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Address = "123 Main Street, Apartment 4B",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400001",
                            State = "Maharashtra",
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateSkillId = new Guid("c76ef1f7-97cb-4498-8f93-f5f360dbe58d"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("eb69f6c7-1999-4eee-a389-7cdf63bcee4b")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("0c1164cb-1249-4d08-bb6e-f4b5f7d3b473"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("54b1a3ea-3a84-4da7-9e80-cb934fa2351b")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("91785c95-2478-461a-9fee-224f74e55097"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("eb278ba1-7b80-40c2-a489-23bb68c1b7c5")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.Property<Guid>("CandidateSocialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocialPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSocialsId");

                    b.HasIndex("SocialPlatformId");

                    b.HasIndex("CandidateProfileId", "SocialPlatformId")
                        .IsUnique();

                    b.ToTable("CandidateSocials");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = new Guid("b3f2c0e1-6f2a-4a6c-9f8a-1a2b3c4d5e01"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science",
                            InstituteName = "St. Xavier's College, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 78.45m,
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("c4d3f1a2-7b3c-4d8e-9a0b-2c3d4e5f6a02"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "Higher Secondary (12th)",
                            EndDate = new DateTime(2016, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "Mumbai Central Higher Secondary School",
                            IsCurrent = false,
                            PercentageScore = 86.20m,
                            StartDate = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("d5e4f3b2-8c4d-4e9f-0a1b-3c4d5e6f7a03"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "InnoTech Solutions Pvt. Ltd.",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on backend APIs using .NET Core, implemented authentication and REST endpoints, wrote unit tests and integrated CI/CD pipelines.",
                            Position = "Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("e6f5a4c3-9d5e-4f0a-1b2c-4d5e6f7a8b04"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "QuickStart Internships",
                            DurationYears = 0.50m,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Assisted in developing small features, bug fixes and wrote documentation. Gained exposure to agile practices.",
                            Position = "Software Intern",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = new Guid("649b2847-c705-4f31-8ee0-497d1da8eb6c"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 23, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5775),
                            DeadlineDate = new DateTime(2026, 1, 22, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5783),
                            JobDescriptionId = new Guid("6fc101eb-ffa3-4d3b-8d6c-f693df819c47"),
                            OpeningsCount = 3
                        },
                        new
                        {
                            JobId = new Guid("71d7f80f-f3ce-45ce-9e8a-65d50559b115"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 26, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5786),
                            DeadlineDate = new DateTime(2026, 1, 25, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5787),
                            JobDescriptionId = new Guid("d542b0e8-54b9-4e34-9531-2b3f478058ae"),
                            OpeningsCount = 2
                        },
                        new
                        {
                            JobId = new Guid("87aee47a-c2e8-4b13-aff1-b6bcbd88ca05"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 28, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5790),
                            DeadlineDate = new DateTime(2026, 1, 27, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5790),
                            JobDescriptionId = new Guid("40c80f60-a85e-440f-8864-408d8413e11f"),
                            OpeningsCount = 1
                        },
                        new
                        {
                            JobId = new Guid("38c7f97d-a42c-45d3-8e4f-e732ff5d8843"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 30, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5799),
                            DeadlineDate = new DateTime(2026, 2, 1, 3, 57, 35, 966, DateTimeKind.Utc).AddTicks(5800),
                            JobDescriptionId = new Guid("198cad1e-709f-48b5-a91e-952f9e27370c"),
                            OpeningsCount = 5
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumExperienceReq")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            JobDescriptionId = new Guid("6fc101eb-ffa3-4d3b-8d6c-f693df819c47"),
                            Details = "We are looking for an experienced .NET developer to join our team. Must have strong C# and ASP.NET Core skills.",
                            JobTypeId = new Guid("5422a1a8-2976-48d5-8560-852a08b889bc"),
                            Location = "Mumbai, India",
                            MinimumExperienceReq = 5,
                            Responsibilty = "Develop and maintain web applications, code reviews, mentor junior developers",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("d542b0e8-54b9-4e34-9531-2b3f478058ae"),
                            Details = "Join our frontend team to build modern web applications using React and TypeScript.",
                            JobTypeId = new Guid("5422a1a8-2976-48d5-8560-852a08b889bc"),
                            Location = "Bangalore, India",
                            MinimumExperienceReq = 3,
                            Responsibilty = "Build responsive UIs, optimize performance, collaborate with designers",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("40c80f60-a85e-440f-8864-408d8413e11f"),
                            Details = "Seeking a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.",
                            JobTypeId = new Guid("6d988fd0-889a-4275-b538-45772d7b408f"),
                            Location = "Remote",
                            MinimumExperienceReq = 4,
                            Responsibilty = "Maintain AWS infrastructure, automate deployments, monitor systems",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("198cad1e-709f-48b5-a91e-952f9e27370c"),
                            Details = "Entry-level position for fresh graduates passionate about Python and data science.",
                            JobTypeId = new Guid("c0f276b1-d13a-4597-aa13-77ec5e3491eb"),
                            Location = "Pune, India",
                            MinimumExperienceReq = 0,
                            Responsibilty = "Write clean code, learn from seniors, contribute to data pipelines",
                            Title = "Junior Python Developer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            JobTypeId = new Guid("5422a1a8-2976-48d5-8560-852a08b889bc"),
                            TypeName = "Full-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("c0f276b1-d13a-4597-aa13-77ec5e3491eb"),
                            TypeName = "Part-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("6d988fd0-889a-4275-b538-45772d7b408f"),
                            TypeName = "Contract"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("eb69f6c7-1999-4eee-a389-7cdf63bcee4b"),
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("54b1a3ea-3a84-4da7-9e80-cb934fa2351b"),
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = new Guid("b230e5bb-59ac-4a6b-8702-452e5eb35ae0"),
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            SkillId = new Guid("f51dae79-5edd-429b-af6c-c9a27ae94720"),
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = new Guid("6f555963-a040-413f-8fdd-13383f9d825b"),
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("eb278ba1-7b80-40c2-a489-23bb68c1b7c5"),
                            IsActive = true,
                            Name = "React"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.SocialPlatform", b =>
                {
                    b.Property<Guid>("SocialPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialPlatformId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            SocialPlatformId = new Guid("36916ed0-575c-4ef3-aa79-a3058e932276"),
                            Name = "LinkedIn"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("13e110fc-90f8-49f7-afc2-48141833c75b"),
                            Name = "GitHub"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("92dce8fc-8c0b-4a78-b7c4-6bca3bb8fed9"),
                            Name = "Portfolio"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("26b9f6f5-d041-435e-99d5-a3483e9394bd"),
                            Name = "Twitter"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("c980b092-79e9-42b0-a1e7-7ca39b446af9"),
                            Name = "Stack Overflow"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a01a33a1-10c5-4424-a74b-0130a086b96e"),
                            CreatedDate = new DateTime(2026, 1, 2, 3, 57, 35, 520, DateTimeKind.Utc).AddTicks(459),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exp.com",
                            Fname = "Admin",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "User",
                            MobileNumber = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDD5Rtx+Jq76jogG0wmXTv/CZH3DnxhGCwXmq0NZHptcRWw76SAGFbpk87TZ9ns/A==",
                            UserRoleId = new Guid("b57751e8-24af-473b-a7aa-ff30ddfc0d49")
                        },
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 2, 3, 57, 35, 601, DateTimeKind.Utc).AddTicks(4515),
                            DOB = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@exp.com",
                            Fname = "Peter",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Parker",
                            MobileNumber = "0987654321",
                            PasswordHash = "AQAAAAIAAYagAAAAEKDWS/RYgNcxg5zLcfAYCcPW8OcspLiZfFK5VcPMp3tPP3cC3oC7r3Uh4BxieqhyCg==",
                            UserRoleId = new Guid("66a24f39-2e0a-46fd-81b5-13d6bddb8c5c")
                        },
                        new
                        {
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733"),
                            CreatedDate = new DateTime(2026, 1, 2, 3, 57, 35, 687, DateTimeKind.Utc).AddTicks(6984),
                            DOB = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abhi@exp.com",
                            Fname = "Abhi",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "G",
                            MobileNumber = "1111111111",
                            PasswordHash = "AQAAAAIAAYagAAAAEJyqSfh/qiaK3SOjWo4EeDcp42sTBoXJLZS1zepxEKSsdTab0rkie+uGK4jUuA607A==",
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc60")
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 2, 3, 57, 35, 777, DateTimeKind.Utc).AddTicks(6122),
                            DOB = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reviewer@exp.com",
                            Fname = "Bruce",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Wayne",
                            MobileNumber = "2222222222",
                            PasswordHash = "AQAAAAIAAYagAAAAEAZYAEtcKg9B/pDgeH18KgwgeefFsDLrlRxIrgTiIOGH4l19PHtlsSZeX8TjxBUjiw==",
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc65")
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 2, 3, 57, 35, 873, DateTimeKind.Utc).AddTicks(145),
                            DOB = new DateTime(1988, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "interviewer@exp.com",
                            Fname = "Tony",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Stark",
                            MobileNumber = "3333333333",
                            PasswordHash = "AQAAAAIAAYagAAAAEKYd7dMPaVajKGpzd1c6E9Xu0KN5hIB9pLZElx4IIVaYrGnuK7Lho6MUj2d+Y9y2Cw==",
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc66")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("b57751e8-24af-473b-a7aa-ff30ddfc0d49"),
                            RoleName = "Admin",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("66a24f39-2e0a-46fd-81b5-13d6bddb8c5c"),
                            RoleName = "Recruiter",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc60"),
                            RoleName = "Candidate",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc65"),
                            RoleName = "Reviewer",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc66"),
                            RoleName = "Interviewer",
                            active = true
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.AssignedReviewer", null)
                        .WithMany("CVReviewStages")
                        .HasForeignKey("AssignedReviewersId");

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedByUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CVStorages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentManagementSystem.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSocials")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.SocialPlatform", "SocialPlatform")
                        .WithMany()
                        .HasForeignKey("SocialPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Navigation("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("CVStorages");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateSocials");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
