// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementSystem.API.Data;

#nullable disable

namespace RecruitmentManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101140141_AddAssignedReviewersAndCVReviewStages")]
    partial class AddAssignedReviewersAndCVReviewStages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Property<Guid>("AssignedReviewersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AssignedReviewersId");

                    b.HasIndex("Uid");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.Property<Guid>("CVReviewStageSid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedReviewersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CVReviewStageSid");

                    b.HasIndex("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("ReviewedByUid");

                    b.ToTable("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.Property<Guid>("CVStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CVStorageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CVStorages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Address = "123 Main Street, Apartment 4B",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400001",
                            State = "Maharashtra",
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateSkillId = new Guid("c9264801-9ad6-4a0a-95a0-3cf7a9a23e13"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("483a3ec0-15fb-45ff-bbab-a070159c49ee")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("7f45299d-ecdc-4712-904b-832e70e6f993"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("e2c5a0d6-de77-4234-861d-656fc07552d1")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("b951b92e-4cb4-4b51-978b-5830335f53ea"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            SkillId = new Guid("395e7296-18ef-4f25-987d-4630871034c9")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.Property<Guid>("CandidateSocialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocialPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSocialsId");

                    b.HasIndex("SocialPlatformId");

                    b.HasIndex("CandidateProfileId", "SocialPlatformId")
                        .IsUnique();

                    b.ToTable("CandidateSocials");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = new Guid("b3f2c0e1-6f2a-4a6c-9f8a-1a2b3c4d5e01"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science",
                            InstituteName = "St. Xavier's College, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 78.45m,
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("c4d3f1a2-7b3c-4d8e-9a0b-2c3d4e5f6a02"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "Higher Secondary (12th)",
                            EndDate = new DateTime(2016, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "Mumbai Central Higher Secondary School",
                            IsCurrent = false,
                            PercentageScore = 86.20m,
                            StartDate = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("d5e4f3b2-8c4d-4e9f-0a1b-3c4d5e6f7a03"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "InnoTech Solutions Pvt. Ltd.",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on backend APIs using .NET Core, implemented authentication and REST endpoints, wrote unit tests and integrated CI/CD pipelines.",
                            Position = "Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("e6f5a4c3-9d5e-4f0a-1b2c-4d5e6f7a8b04"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "QuickStart Internships",
                            DurationYears = 0.50m,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Assisted in developing small features, bug fixes and wrote documentation. Gained exposure to agile practices.",
                            Position = "Software Intern",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = new Guid("d09714b6-5f0c-4682-a38c-9fac543d8f14"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 22, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(330),
                            DeadlineDate = new DateTime(2026, 1, 21, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(341),
                            JobDescriptionId = new Guid("001edd6b-70e4-47c5-a429-300ec0ab611d"),
                            OpeningsCount = 3
                        },
                        new
                        {
                            JobId = new Guid("8d634e54-8b07-48db-acf7-7f8b10607920"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 25, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(350),
                            DeadlineDate = new DateTime(2026, 1, 24, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(351),
                            JobDescriptionId = new Guid("877ae8f6-2188-4bb7-9b84-5ff322ac2d6c"),
                            OpeningsCount = 2
                        },
                        new
                        {
                            JobId = new Guid("c6ab91d6-755a-4440-8015-de43993c1c8c"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 27, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(357),
                            DeadlineDate = new DateTime(2026, 1, 26, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(358),
                            JobDescriptionId = new Guid("54a7c166-bb73-4ec6-9816-4a6427e73706"),
                            OpeningsCount = 1
                        },
                        new
                        {
                            JobId = new Guid("388a20c2-15dc-4e8b-ae38-7a2031b02507"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 29, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(364),
                            DeadlineDate = new DateTime(2026, 1, 31, 14, 1, 40, 419, DateTimeKind.Utc).AddTicks(365),
                            JobDescriptionId = new Guid("293c1c1d-8e65-4c40-a814-aaeeaa428e61"),
                            OpeningsCount = 5
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumExperienceReq")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            JobDescriptionId = new Guid("001edd6b-70e4-47c5-a429-300ec0ab611d"),
                            Details = "We are looking for an experienced .NET developer to join our team. Must have strong C# and ASP.NET Core skills.",
                            JobTypeId = new Guid("2a3af9ef-37ab-4052-948d-239cf13f4cb0"),
                            Location = "Mumbai, India",
                            MinimumExperienceReq = 5,
                            Responsibilty = "Develop and maintain web applications, code reviews, mentor junior developers",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("877ae8f6-2188-4bb7-9b84-5ff322ac2d6c"),
                            Details = "Join our frontend team to build modern web applications using React and TypeScript.",
                            JobTypeId = new Guid("2a3af9ef-37ab-4052-948d-239cf13f4cb0"),
                            Location = "Bangalore, India",
                            MinimumExperienceReq = 3,
                            Responsibilty = "Build responsive UIs, optimize performance, collaborate with designers",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("54a7c166-bb73-4ec6-9816-4a6427e73706"),
                            Details = "Seeking a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.",
                            JobTypeId = new Guid("2f523d6f-e078-43c4-ab35-5522dd8f0362"),
                            Location = "Remote",
                            MinimumExperienceReq = 4,
                            Responsibilty = "Maintain AWS infrastructure, automate deployments, monitor systems",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("293c1c1d-8e65-4c40-a814-aaeeaa428e61"),
                            Details = "Entry-level position for fresh graduates passionate about Python and data science.",
                            JobTypeId = new Guid("c029af51-c008-4cee-a683-7c7b40a960d5"),
                            Location = "Pune, India",
                            MinimumExperienceReq = 0,
                            Responsibilty = "Write clean code, learn from seniors, contribute to data pipelines",
                            Title = "Junior Python Developer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            JobTypeId = new Guid("2a3af9ef-37ab-4052-948d-239cf13f4cb0"),
                            TypeName = "Full-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("c029af51-c008-4cee-a683-7c7b40a960d5"),
                            TypeName = "Part-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("2f523d6f-e078-43c4-ab35-5522dd8f0362"),
                            TypeName = "Contract"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("483a3ec0-15fb-45ff-bbab-a070159c49ee"),
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("e2c5a0d6-de77-4234-861d-656fc07552d1"),
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = new Guid("ea3fd983-a5bb-43aa-a0d3-621036d72427"),
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            SkillId = new Guid("b0b8bbf0-ff47-452d-9e2c-f8153f751155"),
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = new Guid("0a2ab5b9-edb0-4bfa-8e2c-f4f97232c1e4"),
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("395e7296-18ef-4f25-987d-4630871034c9"),
                            IsActive = true,
                            Name = "React"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.SocialPlatform", b =>
                {
                    b.Property<Guid>("SocialPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialPlatformId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            SocialPlatformId = new Guid("bbd3c48c-3a8e-4d4f-896d-bb1db6944c17"),
                            Name = "LinkedIn"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("e18905e3-4906-487d-8586-e3ccbc7028e4"),
                            Name = "GitHub"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("711a7ffe-717b-466c-ba10-0b0cd44971f5"),
                            Name = "Portfolio"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("7c730849-68d0-4e58-a576-c191965a575d"),
                            Name = "Twitter"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("59e8a7b2-0529-4de4-a322-663498817ec1"),
                            Name = "Stack Overflow"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a01a33a1-10c5-4424-a74b-0130a086b96e"),
                            CreatedDate = new DateTime(2026, 1, 1, 14, 1, 40, 3, DateTimeKind.Utc).AddTicks(1036),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exp.com",
                            Fname = "Admin",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "User",
                            MobileNumber = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAECG1iUtwFsCbLpJvieQC4TkFWuL092+iCIjQdr+Ra+yHRKEu07xireejD0lknYJkuw==",
                            UserRoleId = new Guid("b57751e8-24af-473b-a7aa-ff30ddfc0d49")
                        },
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 1, 14, 1, 40, 115, DateTimeKind.Utc).AddTicks(7761),
                            DOB = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@exp.com",
                            Fname = "Peter",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Parker",
                            MobileNumber = "0987654321",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQDzwKB6ZeFw+c9A3a5ZfnLaSpWU5Xc0b5JKzCtVXXpUR3tPEyd96fBP/5883Rpfg==",
                            UserRoleId = new Guid("66a24f39-2e0a-46fd-81b5-13d6bddb8c5c")
                        },
                        new
                        {
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733"),
                            CreatedDate = new DateTime(2026, 1, 1, 14, 1, 40, 244, DateTimeKind.Utc).AddTicks(7251),
                            DOB = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abhi@exp.com",
                            Fname = "Abhi",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "G",
                            MobileNumber = "1111111111",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQKx5BqHTmkKXLoTHcILqVS0zQE9pTyIjdilBSj5GT8XMa/h0mqTwDeB9hST8efmw==",
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc60")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("b57751e8-24af-473b-a7aa-ff30ddfc0d49"),
                            RoleName = "Admin",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("66a24f39-2e0a-46fd-81b5-13d6bddb8c5c"),
                            RoleName = "Recruiter",
                            active = true
                        },
                        new
                        {
                            UserRoleId = new Guid("c016dbd1-11c4-444b-8b3e-84095706fc60"),
                            RoleName = "Candidate",
                            active = true
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVReviewStage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.AssignedReviewer", null)
                        .WithMany("CVReviewStages")
                        .HasForeignKey("AssignedReviewersId");

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedByUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CVStorages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentManagementSystem.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSocials")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.SocialPlatform", "SocialPlatform")
                        .WithMany()
                        .HasForeignKey("SocialPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Navigation("CVReviewStages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("CVStorages");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateSocials");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
