// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManagementSystem.API.Data;

#nullable disable

namespace RecruitmentManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106185937_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.Property<Guid>("ApplicationSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasSkill")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationSkillId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.Property<Guid>("AssignedReviewersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AssignedReviewersId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("Uid");

                    b.ToTable("AssignedReviewers");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.Property<Guid>("CVStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CVStorageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CVStorages");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            Address = "A-304, Sunrise Apartments, Koramangala",
                            City = "Bangalore",
                            Country = "India",
                            PostalCode = "560034",
                            State = "Karnataka",
                            UserId = new Guid("4603558e-87ae-4fea-88c4-9f5c2e188f5e")
                        },
                        new
                        {
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            Address = "B-12, Green Valley Society, Bandra West",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400050",
                            State = "Maharashtra",
                            UserId = new Guid("0f159347-5847-4449-ad7e-8b604ac5a9ac")
                        },
                        new
                        {
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Address = "123 Main Street, Apartment 4B",
                            City = "Mumbai",
                            Country = "India",
                            PostalCode = "400001",
                            State = "Maharashtra",
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExperienceYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateSkillId = new Guid("3fb2b7a0-a492-4ce7-b45d-0a69a1ab3bef"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("cef361e0-7e46-4ae5-b6bc-a4ef8ad0d71d"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("c47f3e8f-a1c9-4298-ac93-9784f64b38dd"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("65a4485d-1e04-4a91-b749-e639f1ad6c93"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("ed2623d9-8a24-48c1-925e-05655e56379e"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 3m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("b88a8be0-fc87-4713-a9c1-abc02a1be5f5")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("a4823745-470b-49d0-a34f-872229e00184"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            ExperienceYears = 2m,
                            ProficiencyLevel = "Beginner",
                            SkillId = new Guid("c46102bc-1749-43bf-b1a5-c5a31827b346")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("18d0c154-5983-4a60-b09d-8fe456742a56"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 6m,
                            ProficiencyLevel = "Expert",
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("e90b2759-00bf-432a-972d-e005782ad34c"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("64f4420e-1c32-4461-85a8-2c4c9341588b"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("372935c5-e750-4c8d-a307-f8b51b038347"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 6m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("b71362e2-d04d-4000-bc48-603fe801ffba"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("03d86258-cd7e-467f-87cb-09609d38571b")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("d4aaa9dc-cf7d-4662-8d82-9ad4b22baf24"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            ExperienceYears = 3m,
                            ProficiencyLevel = "Intermediate",
                            SkillId = new Guid("64b7e1de-546e-47b0-a15b-85364d11037d")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("82036566-cd6f-4e42-af17-6e83d2ea5854"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("222db577-d2d0-4eec-aa42-6263e4e5da76"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            ExperienceYears = 5m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("074cc6c8-637b-4639-b22c-b80a210a9778"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            ExperienceYears = 3m,
                            ProficiencyLevel = "Advanced",
                            SkillId = new Guid("b88a8be0-fc87-4713-a9c1-abc02a1be5f5")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("fcda6750-e3cf-4548-a043-f3d2d3a286e0"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            ExperienceYears = 4m,
                            ProficiencyLevel = "Intermediate",
                            SkillId = new Guid("8b6c6882-ccc8-435f-b991-50e6d47bc9e9")
                        },
                        new
                        {
                            CandidateSkillId = new Guid("2e4bf4c2-e1b0-4c85-b28e-4f79734a1234"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            ExperienceYears = 2m,
                            ProficiencyLevel = "Intermediate",
                            SkillId = new Guid("40624a3a-30ff-47db-8084-c54aa5487d2e")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.Property<Guid>("CandidateSocialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocialPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateSocialsId");

                    b.HasIndex("SocialPlatformId");

                    b.HasIndex("CandidateProfileId", "SocialPlatformId")
                        .IsUnique();

                    b.ToTable("CandidateSocials");

                    b.HasData(
                        new
                        {
                            CandidateSocialsId = new Guid("0552abcc-db6f-49ad-add1-4b224afecd1d"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            Link = "https://linkedin.com/in/priya-sharma-dev",
                            SocialPlatformId = new Guid("50bdf779-682c-4625-8c54-9859d7d7a0e6")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("c7649386-3789-47cf-ac64-eced1122797d"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            Link = "https://github.com/priyasharma",
                            SocialPlatformId = new Guid("0b516f73-50c5-422f-948c-8da253849b27")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("968972b5-2b03-4be3-8664-03f65d179fa1"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            Link = "https://linkedin.com/in/rajesh-kumar-frontend",
                            SocialPlatformId = new Guid("50bdf779-682c-4625-8c54-9859d7d7a0e6")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("64064824-6411-439d-b3fe-cbc2fe60c39d"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            Link = "https://github.com/rajeshkumar-dev",
                            SocialPlatformId = new Guid("0b516f73-50c5-422f-948c-8da253849b27")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("a176e36e-022d-41eb-bfa1-aeee65fc1aff"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            Link = "https://rajeshkumar.dev",
                            SocialPlatformId = new Guid("9cb27dd8-5cd0-4092-ba45-e0b5bdcfbd12")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("7fd7af50-00fd-4884-823a-dea1a58bc3a6"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Link = "https://linkedin.com/in/test-user",
                            SocialPlatformId = new Guid("50bdf779-682c-4625-8c54-9859d7d7a0e6")
                        },
                        new
                        {
                            CandidateSocialsId = new Guid("f906bb36-5f31-4029-aa23-df70a2e24b38"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            Link = "https://github.com/testuser",
                            SocialPlatformId = new Guid("0b516f73-50c5-422f-948c-8da253849b27")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            EducationId = new Guid("3c802d7b-bbca-40e4-a96c-a508824249d8"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            DegreeType = "B.E",
                            EndDate = new DateTime(2017, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science and Engineering",
                            InstituteName = "RV College of Engineering, Bangalore",
                            IsCurrent = false,
                            PercentageScore = 82.50m,
                            StartDate = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("26490411-25df-460e-89f2-9ddff9196a7e"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            DegreeType = "12th Grade",
                            EndDate = new DateTime(2013, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science (PCMC)",
                            InstituteName = "National Public School, Bangalore",
                            IsCurrent = false,
                            PercentageScore = 89.00m,
                            StartDate = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("e5ba47e9-d283-4742-ba40-034916da8c17"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Information Technology",
                            InstituteName = "Mumbai University - DJ Sanghvi College",
                            IsCurrent = false,
                            PercentageScore = 75.20m,
                            StartDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("17293e17-f196-4fbc-8b77-3c720d3e62f4"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            DegreeType = "HSC (12th)",
                            EndDate = new DateTime(2015, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "St. Xavier's High School, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 81.50m,
                            StartDate = new DateTime(2013, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("b3f2c0e1-6f2a-4a6c-9f8a-1a2b3c4d5e01"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "B.Tech",
                            EndDate = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Computer Science",
                            InstituteName = "St. Xavier's College, Mumbai",
                            IsCurrent = false,
                            PercentageScore = 78.45m,
                            StartDate = new DateTime(2016, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EducationId = new Guid("c4d3f1a2-7b3c-4d8e-9a0b-2c3d4e5f6a02"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            DegreeType = "Higher Secondary (12th)",
                            EndDate = new DateTime(2016, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Science",
                            InstituteName = "Mumbai Central Higher Secondary School",
                            IsCurrent = false,
                            PercentageScore = 86.20m,
                            StartDate = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeRoleId");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            IsActive = true,
                            RoleName = "Recruiter"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            IsActive = true,
                            RoleName = "Reviewer"
                        },
                        new
                        {
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            IsActive = true,
                            RoleName = "Interviewer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EmployeeRoleId");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("EmployeeUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            EmployeeRoleId = new Guid("a12961ce-53d2-4294-99cb-b7916dbcec24"),
                            AssignedOn = new DateTime(2026, 1, 6, 18, 59, 34, 825, DateTimeKind.Utc).AddTicks(412)
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            EmployeeRoleId = new Guid("9c0d0137-9b2e-47d5-8dac-8bc00bfd6e49"),
                            AssignedOn = new DateTime(2026, 1, 6, 18, 59, 34, 825, DateTimeKind.Utc).AddTicks(415)
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            EmployeeRoleId = new Guid("041c97a7-8cb7-4476-b7b3-5ff64bbba57f"),
                            AssignedOn = new DateTime(2026, 1, 6, 18, 59, 34, 825, DateTimeKind.Utc).AddTicks(417)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationYears")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = new Guid("3d2b65d7-be01-4045-a93e-b5ce34f02cb5"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            CompanyName = "Infosys Technologies Ltd",
                            DurationYears = 3.50m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Led a team of 4 developers in building enterprise applications using .NET Core and Angular. Implemented microservices architecture, optimized database queries, and mentored junior developers.",
                            Position = "Senior Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("c1d1c8b4-881f-4cdb-a8ed-2f97f652e792"),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            CompanyName = "TCS Digital",
                            DurationYears = 3.00m,
                            EndDate = new DateTime(2020, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Developed and maintained web applications using ASP.NET MVC and SQL Server. Participated in code reviews, unit testing, and agile ceremonies.",
                            Position = "Software Developer",
                            StartDate = new DateTime(2017, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("defbc4eb-bb4f-4549-a64a-4185863c4bcc"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            CompanyName = "Wipro Digital",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Built responsive web applications using React, Redux, and TypeScript. Collaborated with UX designers and backend teams to deliver pixel-perfect interfaces. Improved page load times by 40%.",
                            Position = "Frontend Developer",
                            StartDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("1707a597-c901-44c1-a4b8-1596ee8bc2dd"),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            CompanyName = "Cognizant",
                            DurationYears = 1.50m,
                            EndDate = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on client projects using HTML, CSS, JavaScript, and basic React. Fixed bugs, implemented new features, and learned modern frontend development practices.",
                            Position = "Junior Frontend Developer",
                            StartDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("d5e4f3b2-8c4d-4e9f-0a1b-3c4d5e6f7a03"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "InnoTech Solutions Pvt. Ltd.",
                            DurationYears = 2.50m,
                            EndDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Worked on backend APIs using .NET Core, implemented authentication and REST endpoints, wrote unit tests and integrated CI/CD pipelines.",
                            Position = "Software Engineer",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExperienceId = new Guid("e6f5a4c3-9d5e-4f0a-1b2c-4d5e6f7a8b04"),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CompanyName = "QuickStart Internships",
                            DurationYears = 0.50m,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = false,
                            JobDescription = "Assisted in developing small features, bug fixes and wrote documentation. Gained exposure to agile practices.",
                            Position = "Software Intern",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningsCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JobDescriptionId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 27, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6205),
                            DeadlineDate = new DateTime(2026, 1, 26, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6215),
                            JobDescriptionId = new Guid("9e0ff7b6-48fd-4a0b-acf7-ab19e6586563"),
                            OpeningsCount = 3
                        },
                        new
                        {
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2025, 12, 30, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6217),
                            DeadlineDate = new DateTime(2026, 1, 29, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6218),
                            JobDescriptionId = new Guid("a6aa2872-4447-48e2-86f0-7fb51bb78f37"),
                            OpeningsCount = 2
                        },
                        new
                        {
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 1, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6221),
                            DeadlineDate = new DateTime(2026, 1, 31, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6226),
                            JobDescriptionId = new Guid("2faf5007-a266-49d4-8c97-dc5790b45dae"),
                            OpeningsCount = 1
                        },
                        new
                        {
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            CreatedByUserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 3, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6229),
                            DeadlineDate = new DateTime(2026, 2, 5, 18, 59, 34, 826, DateTimeKind.Utc).AddTicks(6229),
                            JobDescriptionId = new Guid("79ce823e-e1f1-452b-b485-4e8268c18f75"),
                            OpeningsCount = 5
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            JobApplicationId = new Guid("a7a32744-a9be-4d15-9410-0b44d3b959d5"),
                            ApplicationDate = new DateTime(2025, 12, 29, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6191),
                            CandidateProfileId = new Guid("67bfaed4-2f6b-4dbc-aa3e-6d257300d72c"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            StatusUpdatedAt = new DateTime(2025, 12, 29, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6196)
                        },
                        new
                        {
                            JobApplicationId = new Guid("96637b5d-61b1-45e0-8813-38dd76f0b8a2"),
                            ApplicationDate = new DateTime(2025, 12, 30, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6241),
                            CandidateProfileId = new Guid("984e06f1-bb17-4bd9-a8ad-6cee04841e8f"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            StatusUpdatedAt = new DateTime(2025, 12, 30, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6242)
                        },
                        new
                        {
                            JobApplicationId = new Guid("d61d7f07-8593-409c-bbeb-fcd63263157c"),
                            ApplicationDate = new DateTime(2025, 12, 31, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6270),
                            CandidateProfileId = new Guid("29d665b6-7013-4170-a8eb-844f2d79d356"),
                            CurrentStatus = "Applied",
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            StatusNote = "Application received",
                            StatusUpdatedAt = new DateTime(2025, 12, 31, 18, 59, 34, 828, DateTimeKind.Utc).AddTicks(6272)
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumExperienceReq")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            JobDescriptionId = new Guid("9e0ff7b6-48fd-4a0b-acf7-ab19e6586563"),
                            Details = "We are looking for an experienced .NET developer to join our team. Must have strong C# and ASP.NET Core skills.",
                            JobTypeId = new Guid("6ee1eb42-f820-4b07-8e5b-21aada900f71"),
                            Location = "Mumbai, India",
                            MinimumExperienceReq = 5,
                            Responsibilty = "Develop and maintain web applications, code reviews, mentor junior developers",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("a6aa2872-4447-48e2-86f0-7fb51bb78f37"),
                            Details = "Join our frontend team to build modern web applications using React and TypeScript.",
                            JobTypeId = new Guid("6ee1eb42-f820-4b07-8e5b-21aada900f71"),
                            Location = "Bangalore, India",
                            MinimumExperienceReq = 3,
                            Responsibilty = "Build responsive UIs, optimize performance, collaborate with designers",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("2faf5007-a266-49d4-8c97-dc5790b45dae"),
                            Details = "Seeking a DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.",
                            JobTypeId = new Guid("09c3576e-2b5e-4973-9dea-c6485b8a733a"),
                            Location = "Remote",
                            MinimumExperienceReq = 4,
                            Responsibilty = "Maintain AWS infrastructure, automate deployments, monitor systems",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobDescriptionId = new Guid("79ce823e-e1f1-452b-b485-4e8268c18f75"),
                            Details = "Entry-level position for fresh graduates passionate about Python and data science.",
                            JobTypeId = new Guid("bec262d6-f5d8-44c6-b80a-20699c3012a2"),
                            Location = "Pune, India",
                            MinimumExperienceReq = 0,
                            Responsibilty = "Write clean code, learn from seniors, contribute to data pipelines",
                            Title = "Junior Python Developer"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.Property<Guid>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSkillId");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            JobSkillId = new Guid("249edd52-4bfe-4528-8ac3-9fbea5c11bdc"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 5,
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882")
                        },
                        new
                        {
                            JobSkillId = new Guid("20928977-ee64-4974-b67d-5893382521a0"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6")
                        },
                        new
                        {
                            JobSkillId = new Guid("ef99ecc6-b6b4-4510-a5cc-be9b250c892f"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0")
                        },
                        new
                        {
                            JobSkillId = new Guid("ce18b342-3429-4198-8532-dc162d4f36f1"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895")
                        },
                        new
                        {
                            JobSkillId = new Guid("59623389-6c75-41f2-b953-c7730dfaca2a"),
                            JobId = new Guid("a83a2e30-7d33-4829-bf86-e9cce7462b53"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("03d86258-cd7e-467f-87cb-09609d38571b")
                        },
                        new
                        {
                            JobSkillId = new Guid("a89f2847-1f1a-4b5d-93f5-a81cc7aabee6"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0")
                        },
                        new
                        {
                            JobSkillId = new Guid("4cbbafc5-8ab0-4bd1-ae3b-5dfc34ff6a0a"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868")
                        },
                        new
                        {
                            JobSkillId = new Guid("cfa5265f-6908-43f1-a15c-ce5d146315cd"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("b88a8be0-fc87-4713-a9c1-abc02a1be5f5")
                        },
                        new
                        {
                            JobSkillId = new Guid("ba158853-30e2-46d6-ba8a-d56f223e4cdf"),
                            JobId = new Guid("af6b7d6b-2128-4e5f-8804-d5209a38e443"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("8b6c6882-ccc8-435f-b991-50e6d47bc9e9")
                        },
                        new
                        {
                            JobSkillId = new Guid("c7f6645e-ef61-450f-aa5e-bddb77be5d85"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 4,
                            SkillId = new Guid("4ee9ab25-f239-42dd-93e9-203749c9a8a7")
                        },
                        new
                        {
                            JobSkillId = new Guid("41204854-f400-4527-8722-ab1e5cc3a157"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("b4c75a72-9a14-4c89-94e3-5ebdfd5c04d6")
                        },
                        new
                        {
                            JobSkillId = new Guid("5382c6f9-464d-4d2c-a082-aaaf6d766434"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 2,
                            SkillId = new Guid("068ad609-d1cf-4945-aaf1-1914d10402ed")
                        },
                        new
                        {
                            JobSkillId = new Guid("ef7540f6-c9e0-4aec-a561-d8f1a5eca99f"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("79891c3c-4052-4206-b2ef-a7608bb093a1")
                        },
                        new
                        {
                            JobSkillId = new Guid("d24ce563-8785-4021-b572-fd5bc68a1fd9"),
                            JobId = new Guid("f9651a24-9357-4af0-a9f0-96f5736e8eb6"),
                            MinExperienceYears = 3,
                            SkillId = new Guid("8b6c6882-ccc8-435f-b991-50e6d47bc9e9")
                        },
                        new
                        {
                            JobSkillId = new Guid("d5863eb1-3129-4789-bee7-7a993726e596"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("4c487bbc-6fa9-4643-9d9e-a88e5bea917e")
                        },
                        new
                        {
                            JobSkillId = new Guid("7f47b809-2a0e-47ee-956d-61183c4da696"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("67ddb3fd-f7ce-4797-af87-9a6842e6d2ef")
                        },
                        new
                        {
                            JobSkillId = new Guid("38e9f232-1480-45f2-9e32-2a8c044bd4d8"),
                            JobId = new Guid("15697654-2e8e-412b-b35e-8226cf911237"),
                            MinExperienceYears = 0,
                            SkillId = new Guid("8b6c6882-ccc8-435f-b991-50e6d47bc9e9")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            JobTypeId = new Guid("6ee1eb42-f820-4b07-8e5b-21aada900f71"),
                            TypeName = "Full-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("bec262d6-f5d8-44c6-b80a-20699c3012a2"),
                            TypeName = "Part-Time"
                        },
                        new
                        {
                            JobTypeId = new Guid("09c3576e-2b5e-4973-9dea-c6485b8a733a"),
                            TypeName = "Contract"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.Property<Guid>("ReviewCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommentedByUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewCommentId");

                    b.HasIndex("CommentedByUid");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("43ff8410-b479-4846-956a-df3c56ffd882"),
                            IsActive = true,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("cc858b5f-73d0-4933-880d-3ca36cdfd2c6"),
                            IsActive = true,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = new Guid("355e3b35-1706-480c-b5ab-6be7707b49e0"),
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            SkillId = new Guid("d161a587-31d4-45ea-a184-80495bdf6895"),
                            IsActive = true,
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = new Guid("07a14cde-7266-405a-9fa8-8a71554c7868"),
                            IsActive = true,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("1798cda1-f1ef-45e6-9bbc-e9ca5970c5c0"),
                            IsActive = true,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = new Guid("4c487bbc-6fa9-4643-9d9e-a88e5bea917e"),
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("92dc292b-9df8-419a-8424-8939f94f3c98"),
                            IsActive = true,
                            Name = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("64b7e1de-546e-47b0-a15b-85364d11037d"),
                            IsActive = true,
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("c46102bc-1749-43bf-b1a5-c5a31827b346"),
                            IsActive = true,
                            Name = "Azure"
                        },
                        new
                        {
                            SkillId = new Guid("4ee9ab25-f239-42dd-93e9-203749c9a8a7"),
                            IsActive = true,
                            Name = "AWS"
                        },
                        new
                        {
                            SkillId = new Guid("b4c75a72-9a14-4c89-94e3-5ebdfd5c04d6"),
                            IsActive = true,
                            Name = "Docker"
                        },
                        new
                        {
                            SkillId = new Guid("068ad609-d1cf-4945-aaf1-1914d10402ed"),
                            IsActive = true,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            SkillId = new Guid("67ddb3fd-f7ce-4797-af87-9a6842e6d2ef"),
                            IsActive = true,
                            Name = "MongoDB"
                        },
                        new
                        {
                            SkillId = new Guid("c21098f7-038e-466c-967d-2c64189c27e6"),
                            IsActive = true,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            SkillId = new Guid("8b6c6882-ccc8-435f-b991-50e6d47bc9e9"),
                            IsActive = true,
                            Name = "Git"
                        },
                        new
                        {
                            SkillId = new Guid("79891c3c-4052-4206-b2ef-a7608bb093a1"),
                            IsActive = true,
                            Name = "Jenkins"
                        },
                        new
                        {
                            SkillId = new Guid("b88a8be0-fc87-4713-a9c1-abc02a1be5f5"),
                            IsActive = true,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("40624a3a-30ff-47db-8084-c54aa5487d2e"),
                            IsActive = true,
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("03d86258-cd7e-467f-87cb-09609d38571b"),
                            IsActive = true,
                            Name = "REST API"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.SocialPlatform", b =>
                {
                    b.Property<Guid>("SocialPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialPlatformId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SocialPlatforms");

                    b.HasData(
                        new
                        {
                            SocialPlatformId = new Guid("50bdf779-682c-4625-8c54-9859d7d7a0e6"),
                            Name = "LinkedIn"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("0b516f73-50c5-422f-948c-8da253849b27"),
                            Name = "GitHub"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("9cb27dd8-5cd0-4092-ba45-e0b5bdcfbd12"),
                            Name = "Portfolio"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("ea5b4b2a-070c-45d8-8a6b-383e98d669d6"),
                            Name = "Twitter"
                        },
                        new
                        {
                            SocialPlatformId = new Guid("077827b9-1561-471d-8a02-455d46d415f4"),
                            Name = "Stack Overflow"
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a01a33a1-10c5-4424-a74b-0130a086b96e"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 33, 745, DateTimeKind.Utc).AddTicks(1076),
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exp.com",
                            Fname = "Admin",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "User",
                            MobileNumber = "1234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAEOkSIsZwPzqqRRPBPdlBrKwKDgJxubmvGLkrO2NJzZ42v3YnVTCpEiSvArDbu8tvHw==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("331a9809-54d9-43c3-883a-493e8787f97a"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 33, 838, DateTimeKind.Utc).AddTicks(5707),
                            DOB = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@exp.com",
                            Fname = "Peter",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Parker",
                            MobileNumber = "0987654321",
                            PasswordHash = "AQAAAAIAAYagAAAAEErV+1lKS7JC/bTUNWjLEUf7pSdqPvT5eTodRatkRtZMRPMdhVrJKLC272cY8LlhdA==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("7c6a8f5b-9b2e-4e4a-a1a1-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 33, 934, DateTimeKind.Utc).AddTicks(8180),
                            DOB = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reviewer@exp.com",
                            Fname = "Bruce",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Wayne",
                            MobileNumber = "2222222222",
                            PasswordHash = "AQAAAAIAAYagAAAAENDrQKkjIeR1TUWCBfEBALzc5g1yHlxGVnzF04Cbsb/Od9KBm2NT4jcBHEEyI/BTIA==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("8d7b9a6c-4c3f-4b5d-b2b2-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 35, DateTimeKind.Utc).AddTicks(5188),
                            DOB = new DateTime(1988, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "interviewer@exp.com",
                            Fname = "Tony",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Stark",
                            MobileNumber = "3333333333",
                            PasswordHash = "AQAAAAIAAYagAAAAECS8Il7ciZEwHbamBQplioE3KwETYAX20XfVcIVJdRBNGM1tDdVnW39gV17uPgwZzQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("4603558e-87ae-4fea-88c4-9f5c2e188f5e"),
                            CreatedDate = new DateTime(2025, 7, 6, 18, 59, 34, 134, DateTimeKind.Utc).AddTicks(2457),
                            DOB = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.sharma@email.com",
                            Fname = "Priya",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Sharma",
                            MobileNumber = "9876543210",
                            PasswordHash = "AQAAAAIAAYagAAAAEMbeUjC0/QUFpfv7JR2Lwnvt0/LwcqCyv+zec9UNt8yJ2Qd7roopkhsTLVaguC96yg==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("0f159347-5847-4449-ad7e-8b604ac5a9ac"),
                            CreatedDate = new DateTime(2025, 9, 6, 18, 59, 34, 240, DateTimeKind.Utc).AddTicks(1043),
                            DOB = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rajesh.kumar@email.com",
                            Fname = "Rajesh",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Kumar",
                            MobileNumber = "9876543211",
                            PasswordHash = "AQAAAAIAAYagAAAAEJluFJ1RsMEpEsdEjWddVFa0fGe5d6YLZvpsnK4XY1kK2YEDIMvQOgyXBTVF2Sab1g==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("0a33c200-c9f2-4547-810a-b3337a72d733"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 336, DateTimeKind.Utc).AddTicks(9785),
                            DOB = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abhi@exp.com",
                            Fname = "Abhi",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "G",
                            MobileNumber = "1111111111",
                            PasswordHash = "AQAAAAIAAYagAAAAEBRYtjrP5FdwVfLgac/2KHRVDTTrQlnQ0+smGuYGOPPzAvCQ91sTcmIew58FVVP3Xw==",
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122")
                        },
                        new
                        {
                            UserId = new Guid("9b3048b1-3024-45b0-bb1a-4d29bda2f32b"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 438, DateTimeKind.Utc).AddTicks(7313),
                            DOB = new DateTime(1990, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@exp.com",
                            Fname = "Rahul",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Sharma",
                            MobileNumber = "9000000001",
                            PasswordHash = "AQAAAAIAAYagAAAAEGHWEje0UKqDqjpzfdI0ZY21os3UYXKCHLY1Mzk8XIcR2neEDAI6hdtbm+BjzU7V7Q==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("db13c8ce-7469-4b70-89ad-4bf0a637d78c"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 539, DateTimeKind.Utc).AddTicks(8740),
                            DOB = new DateTime(1992, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya@exp.com",
                            Fname = "Priya",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Verma",
                            MobileNumber = "9000000002",
                            PasswordHash = "AQAAAAIAAYagAAAAECLssCEtq6FqaWdW4eYMRRrrX+6sje27nKk8c8W2GG4e+VJUPDy2iHpig9/6QdKKtw==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("07253644-addb-48db-be8d-0164e41586dd"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 637, DateTimeKind.Utc).AddTicks(7812),
                            DOB = new DateTime(1989, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amit@exp.com",
                            Fname = "Amit",
                            Gender = "Male",
                            IsActive = true,
                            Lname = "Kumar",
                            MobileNumber = "9000000003",
                            PasswordHash = "AQAAAAIAAYagAAAAEIIijrT+fYCtbCtosftI8OQA/kMFnaZtyfX5w8GmeVkUD6sOlFZv7uhaq4YTCOZ9Ww==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        },
                        new
                        {
                            UserId = new Guid("1e89c149-5c9f-4492-b55d-60bf897da9ae"),
                            CreatedDate = new DateTime(2026, 1, 6, 18, 59, 34, 730, DateTimeKind.Utc).AddTicks(5546),
                            DOB = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sneha@exp.com",
                            Fname = "Sneha",
                            Gender = "Female",
                            IsActive = true,
                            Lname = "Reddy",
                            MobileNumber = "9000000004",
                            PasswordHash = "AQAAAAIAAYagAAAAEKToU1R1kuAyk8OEdFVbisuaBxTWKBE2Z4vHPsMQ43IgjW05J1ezixxJGATitu3kfQ==",
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e")
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Property<Guid>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = new Guid("e91d74b9-67cb-41b5-9581-338a64a45122"),
                            TypeName = "Candidate",
                            active = true
                        },
                        new
                        {
                            UserTypeId = new Guid("3b5143aa-62f9-49b8-ba06-3ae28505528e"),
                            TypeName = "Employee",
                            active = true
                        });
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ApplicationSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.AssignedReviewer", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", null)
                        .WithMany("AssignedReviewers")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CVStorage", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CVStorages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitmentManagementSystem.API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateSocial", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSocials")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.SocialPlatform", "SocialPlatform")
                        .WithMany()
                        .HasForeignKey("SocialPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("SocialPlatform");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Education", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeUserRole", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "User")
                        .WithMany("EmployeeUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Experience", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobSkill", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.ReviewComment", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.User", "CommentedBy")
                        .WithMany()
                        .HasForeignKey("CommentedByUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitmentManagementSystem.API.Models.JobApplication", "JobApplication")
                        .WithMany("ReviewComments")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedBy");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.HasOne("RecruitmentManagementSystem.API.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.CandidateProfile", b =>
                {
                    b.Navigation("CVStorages");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateSocials");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.EmployeeRole", b =>
                {
                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.JobApplication", b =>
                {
                    b.Navigation("ApplicationSkills");

                    b.Navigation("AssignedReviewers");

                    b.Navigation("ReviewComments");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployeeUserRoles");
                });

            modelBuilder.Entity("RecruitmentManagementSystem.API.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
